### ISSUE TITLE
 java.lang.NoClassDefFoundError: kotlin/enums/EnumEntriesKt

### ISSUE THREAD

**Issue by bpasson** [usefulness/webp-imageio#198]
When using the v0.8.0 it throws the following exception:

```
Exception in thread "priorityThreadPoolTaskExecutor-1" java.lang.NoClassDefFoundError: kotlin/enums/EnumEntriesKt
	at com.luciad.imageio.webp.CompressionType.<clinit>(CompressionType.kt:5)
	at com.luciad.imageio.webp.WebPWriteParam.<init>(WebPWriteParam.kt:15)
	at com.luciad.imageio.webp.WebPWriter.getDefaultWriteParam(WebPWriter.kt:42)
	at com.luciad.imageio.webp.WebPWriter.write(WebPWriter.kt:53)
	at java.desktop/javax.imageio.ImageWriter.write(ImageWriter.java:613)
	at java.desktop/javax.imageio.ImageIO.doWrite(ImageIO.java:1630)
	at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1596)
```

As far as I can see this has to do with the dependency on `org.jetbrains.kotlin:kotlin-stdlib:1.6.21` which does not have this class.

**Comment by mateuszkwiecinski** [comment]
Hey 👋 it looks like your project manually downgrades the stdlib dependency. AFAICS `0.8.0` ships with transitive dependency to Kotlin's stdlib of version [1.9.22](https://repo1.maven.org/maven2/com/github/usefulness/webp-imageio/0.8.0/webp-imageio-0.8.0.pom) 👀
Please review your project setup, I don't believe there is anything one can do on the library side.

**Comment by bpasson** [comment]
I will try to find the reason. Never seen this before. Will update if I know more.

**Comment by bpasson** [comment]
You are correct. I found the culprit. Somewhere in the dependency hell a kotlin was fixed to a specific version.
